### ISSUE TITLE
Could not render to PNG

### ISSUE THREAD

**Issue by unrealsolver** [CraveFood/avinit#10]
CairoSVG fails to render SVG to PNG with this error.
Solution: Add `viewBox` attribute to `svg`
Error:
```
Traceback (most recent call last):
  File "/home/ruslan/dev/tully/management-backend/application/user/tests/test_avatar.py", line 36, in test_upload
    media_url = self.avatar.upload(user, svg_img)
  File "/home/ruslan/dev/tully/management-backend/application/user/module/avatar.py", line 32, in upload
    cairosvg.svg2png(
  File "/home/ruslan/dev/tully/management-backend/venv/lib/python3.8/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/home/ruslan/dev/tully/management-backend/venv/lib/python3.8/site-packages/cairosvg/surface.py", line 136, in convert
    instance.finish()
  File "/home/ruslan/dev/tully/management-backend/venv/lib/python3.8/site-packages/cairosvg/surface.py", line 519, in finish
    self.cairo.write_to_png(self.output)
  File "/home/ruslan/dev/tully/management-backend/venv/lib/python3.8/site-packages/cairocffi/surfaces.py", line 678, in write_to_png
    _check_status(cairo.cairo_surface_write_to_png(
  File "/home/ruslan/dev/tully/management-backend/venv/lib/python3.8/site-packages/cairocffi/__init__.py", line 88, in _check_status
    raise exception(message, status)
OSError: [Errno cairo returned CAIRO_STATUS_WRITE_ERROR: b'error while writing to output stream'] 11
```

**Comment by unrealsolver** [comment]
Unrelated.
Issue was in the path (output directory did not exist)
